import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ConnectButton } from "../components/Connect";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Ethereum Raffle</h1>
        <a className={styles.sub_title}>
          a decentralized lottery app, currently avalible only on rinkeby
          network
        </a>
        <div className={styles.grid}>
          <p>Players joined - 3</p>
          <p>Entrance Fee - 0.1 ETH</p>
          <p>Recent Winner</p>
        </div>
        <ConnectButton />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
